version: "3.8"

services:
  stockpulse:
    build: ./
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ~/.aws:/root/.aws
    environment:
      - UVICORN_RELOAD=true
      - APP_ENV=development
      - AWS_PROFILE=default
    env_file:
      - .env.development

